#!/usr/bin/env bash
# Copyright (C) 2000,2017 by Massimiliano Ghilardi
# HedgeyTTY fork branding updates
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

FIRSTARG=1
MODE=normal
DPY=

for ARG
do
  if [ "$FIRSTARG" = 1 ]; then
    set --
    FIRSTARG=0
  fi
  if [ "$MODE" = normal ]; then
    case "$ARG" in
      -h|--help|-help )
        echo "Usage: htstart [OPTIONS]
Attach a running hedgeytty server to a display or start a new server.
If a hedgeytty server is found, \`htdisplay' is used to attach it to a display,
else a new hedgeytty server is started.

Currently known options:

 -h, --help            show this help and exit
 --hedgeytty@<HTDISPLAY>  specify server to contact instead of autodetecting it
 <HTDISPLAY>           shortcut for --hedgeytty@<HTDISPLAY>
 --                    end of options: pass further args to hedgeytty or htdisplay
 --<OPTION>            other options are passed verbatim to hedgeytty or htdisplay
"
        exit 0
        ;;
      -- )
        MODE=literal
        ;;
      --hedgeytty@*|--twin@* )
        DPY="${ARG#*@}"
        ;;
      -hedgeytty@*|-twin@* )
        DPY="${ARG#*@}"
        ;;
      :* )
        DPY="$ARG"
        ;;
      * )
        set -- "$@" "$ARG"
        ;;
    esac
  else
    set -- "$@" "$ARG"
  fi
done

export PATH="${PATH:-/usr/bin}"

if [ -n "$DPY" ]; then
  export HTDISPLAY="$DPY"
fi

if htfindtwin >/dev/null 2>&1; then
  exec htdisplay "$@"
else
  exec hedgeytty "$@"
fi
